language: node_js
node_js:
  - 5.6.0
branches:
  only:
    - master
env:
  global:
    - GIT_COMMIT_USER="Travis-CI"
    - GIT_COMMIT_EMAIL="travis@travis-ci.org"
    - secure: qVtM1y/BbIJHERkgG8UqYSxVc2JOun/hDPpgX9Vlaxx1PD1c2TxfHBCo/DaEo8B+j1iYhppwqvgimowLCtIGjlD2GM/Ey1yfqMj4kWNfTVdKSzR1a2E3KddrXqWmX53PP3a5Kw00GHVufBt2wP0kf27WndkWF1onv1n3M/iFucH6n35msmoeuNCuwTXyLAAfxW6idFm9HBfLBH5HhFiTKQmRzLj3IidYsG8uQU6EwLULmbu1+DvAB7fghpv/TyEU5m9oOJqXKD/jrTOjR3EN9qRX8KpPvj6ExjB3uLanutFW03Gp2x/6a3iaYbn2oBJ5rRId648JQT5RDVGJOdU+7etbdpDtkH6pyDNY7uH46mAj4FAeAXQzDdWUw5aMyiDjjESm+uxwEkHjNDCE+kAX87UylUDBT2aLPVWigoE6XS+rqT5prXtQ/hiEJwZD9YgcrjyEMet+XVbcVMfrSz4Yr/OqFbz/yaZLijPUVkaBMA8Rz5RHOrN6KHRJ6bJq2ZlCuhCjpJwaf1YFTV46AELw71hWp/Rfcr9ZvqbE6W1oAIQhftJx4fhOn46fX9os4LGSusiYldsmPMvN1u0RfZUMNWtyc0OLN5TPLpDR9CqS7GNYsoRtdK9MGU7lflbfmDRNQSCC4aakviHI16VOMHkHJxmkllKPvYXgdhX/aB0N+TU=

script:
  - npm install -g git-credential-env
  - git config --global credential.helper "env --username=GIT_USER_NAME"
  - git config --global user.name $GIT_COMMIT_USER
  - git config --global user.email $GIT_COMMIT_EMAIL
  - npm run deploy
