language: node_js
node_js:
  - 6.3.0
branches:
  only:
    - master
env:
  global:
    - secure: "MnqMMmgin+IT8t1cOB1NqX3eEGif5/8/SFQ9qneb8OkT9A+//lz9hJdEexLrymYacNr/tIAY3/4XXSgHbglD2puau48NRjQ2PO3fenTS0hU2XfNQqihdImDn8P6exlCNDehlUjrs0bD7J8fIZWncPskXuAzGAIcTgLZ3shj1Uk2A/t3mhJ1VGmLsJafuFeeKZ7rJ20I5E9pEa/1bF7+58XVzn81viB2Wn+iYRRrE/FqGYzfwfHqmi1EKWSKH5wjRZ0nPtUI8zQ8vK8qCJz1lNRcvO/VI37/4cvcwi/qxAUzYQVY5O/TofIYTPXAgFTXc6sVddCuDtjMbuy4RS63IGBimDG2VBSibKAB44deQSJ4DQr/z8NHQI3cEMfU0wfT0xjyuDtf0JJnZrp+P+o+4yjJICSG4XqSCy15IlOeiTPFdIkdtyR0w+8efXyc0hRBxuqP47CMnh2hi97pFno4XTfH4szm1h8nlCy7liT+2qVFQsFe3iCr5S2c7EO/IZrZFgqeSX8AyR7LHTmUh079h4+kPYQ556YZVEOGBrMKTl0PIdmcWEcdV/iW8tpeaWVSx0AeHMnlxeQypf4HyuEIF9gQ1WytneRE1u/XGCrG9V4j718apMmIODaLOoH3zNheegNF1TSsE/wKlnu8QGA2X6p9IKP+CcnnDvqLHSo3nqVA="

script:
  - git config credential.helper "$PWD/node_modules/.bin/git-credential-env --username=GITHUB_TOKEN"
  - git config user.name "Travis CI"
  - git config user.email builds@travis-ci.org
  - npm run deploy

notifications:
  email:
    on_success: never
    on_failure: always
